default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fridgefriends_development
  name: fridgefriends
  port: 5432
  server: localhost


test:
  <<: *default
  database: fridgefriends_test

production:
  <<: *default
  url: <%= ENV['POSTGRESQL_ADDON_URI'] %>
