meta_product_name: "Fridge Friends"
meta_title: "Fridge Friends - Ne jette plus ta nourriture, donne-la !"
meta_description: "L'application Fridge Friends organise pour toi le don de nourriture.

Tes proches pourront choisir les denrées que tu ne pourras pas consommer à temps. Au lieu de les jeter, propose-leur gratuitement de passer les prendre !"
meta_image: "cover.png"
